### ISSUE TITLE
How about the performance of energy function == [mrn, mrn_shuf, mrn_pot_shuf]?

### ISSUE THREAD

**Issue by Jackory** [MichalBortkiewicz/JaxGCRL#5]
Great work! 
As demonstrated by the ICML24 paper (https://arxiv.org/abs/2406.17098), the critic function equals the temporal distance when the energy function is equal to mrn_pot_shuf. I am curious about their performance, as it is not discussed in your paper.

**Comment by MichalBortkiewicz** [comment]
Hi @Jackory , thanks for your kind words!

We have not thoroughly assessed this critic function to include it in our paper, and we are not fully certain about its implementation. If you would like to run some experiments with it, I'm happy to help!
