### ISSUE TITLE
Bug in pusher: Object gets inside the agent

### ISSUE THREAD

**Issue by FaisalAhmed0** [MichalBortkiewicz/JaxGCRL#9]
![Screenshot from 2024-11-08 11-16-13](https://github.com/user-attachments/assets/622f6cf1-f225-476c-9877-e9a09c8eabc5)
Hello, 
I am using this codebase for my project and when I run experiment on the pusher_easy environment the object gets inside the agent and the agent can not grasp it anymore.

**Comment by MichalBortkiewicz** [comment]
@FaisalAhmed0 , thank you for bringing this up. Which Brax version are you currently using? We haven't seen such behavior in Brax 0.10.5
